# Generated by Django 4.2.5 on 2023-09-12 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_user_managers_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('7ea668b2-c030-4aeb-a772-1c9911c3676e'), editable=False, unique=True),
        ),
    ]
